### ISSUE TITLE
Provide a sdist (or git tag), in-tree LICENSE for py-horned-owl 0.2.1

### ISSUE THREAD

**Issue by bollwyvl** [jannahastings/py-horned-owl#11]
Hello! This looks like an interesting tool, and I would like to take a shot at providing it (and all its platform-specific builds) on [`conda-forge`](https://conda-forge.org/). We'd be able to support building the "big three" x86-64 platforms, as well as some additional ones,  for modern pythons (e.g. 3.8+).

Like a lot of "system-style" package managers, `conda-forge` prefer to use a "canonical" source distribution (such as a `.tar.gz` uploaded to PyPI). Lacking that, a GitHub release tarball is _usually_ fine, but the cryptography sums can change over time. So the big request here is either:

- [ ] upload an `sdist` to go with the `.whl`
- [ ] add a tag for when 0.2.1 was shipped

And:

- [ ] add an explicit LICENSE to the repo (and probably as-released metadata)

If broader distribution is interesting to the maintainers of this package, we always love to have upstream maintainers join the maintainer team, but certainly not required! Once everything "works," it's mostly a matter of pressing "merge" on automated PRs that update version numbers and crypto hashes when new upstream releases come out.

Thanks again!

**Comment by b-gehrke** [comment]
Thank you for your request. The license (LGPL) is added and there are now releases with binaries and sources for versions 0.2.1 and 0.2.2.
