### ISSUE TITLE
Add parsers and serializers for other OWL serialization formats

### ISSUE THREAD

**Issue by cmungall** [jannahastings/py-horned-owl#18]
https://jannahastings.github.io/py-horned-owl/generated/pyhornedowl.open_ontology.html#pyhornedowl.open_ontology

Says "Only .owl and .owx files are currently supported."

`.owl` could be any syntax, but it looks like this means OWL layered as RDF/XML.

Are there any plans to support other syntaxes? I believe these are supported in the rust layer.

https://github.com/phillord/horned-owl/tree/main/src/io/ofn

For saving, only `.owx` is supprted:

https://jannahastings.github.io/py-horned-owl/generated/pyhornedowl.PyIndexedOntology.html#pyhornedowl.PyIndexedOntology.save_to_file

**Comment by cmungall** [comment]
Seems easy, I may try it:

https://github.com/jannahastings/py-horned-owl/blob/38e08833e40d5e42d61dccfb6704e5e8d3372272/src/lib.rs#L581-L645

**Comment by b-gehrke** [comment]
Thank you for the implementation of the functional parsing! I think, adding support for all serializations supported by Horned-OWL is a good idea. I'll have a look.

**Comment by cmungall** [comment]
If you think the style is OK I could add others (there is a bit of code repetition but my rust skills are not good enough to know the best way to abstract)

For my purposes, it would also be very useful to pass in a string rather than a file path and have that be parsed, but I don't know if horned-owl allows this (it would be possible to simulate this with tempfiles, but that's a bit awkward)

**Comment by jamesaoverton** [comment]
@cmungall I've been thinking about this topic. Full support for multiple parsers and serializers with (Py)Horned-OWL would be great. Right now I'm running into some practical limitations:

In recent testing I saw that Horned OWL can roundtrip ontologies such as OBI as long as they're in OWX format, but its RDF/XML parser drops some triples and the roundtrip fails. I'll follow up with a more detailed issue when I have time.

Also, although there was some effort to make Horned OWL's RDF/XML serializer exactly match with OWLAPI, that's a high bar. Without perfect duplication, RDF/XML files stored in git will have spurious differences depending on whether they came out of Horned OWL or OWLAPI.

So for OBO use cases where we want to read and write a `foo-edit.owl` RDF/XML file for version control, at least for now, I think we'll need a `robot convert` step that will use OWLAPI to normalize the serialization. As long as that step is necessary, we can also use ROBOT to convert RDF/XML to OWX or whatever other syntax.

One day I hope we can do most of these steps without requiring the user to have a Java Virtual Machine installed, but we're not there yet.

**Comment by cmungall** [comment]
Thanks

Yes, I agree canonical serialization is a high bar, especially for rdfxml

Canonical serialization would be nice for ofn however as that’s typically
what’s used for the edit file

The dropping of triples is worrisome though…
