### ISSUE TITLE
Adding windows wheels

### ISSUE THREAD

**Issue by Eugenio2192** [jannahastings/py-horned-owl#2]
Hello @jannahastings,

I built some windows wheels using github actions. One can find them here: https://github.com/Eugenio2192/py-horned-owl/releases 
I did them using a branch of your latest release and the development version of https://github.com/phillord/horned-owl 
I have been using them and so far they have been working properly.

I could adapt this github action: https://github.com/Eugenio2192/py-horned-owl/blob/build/.github/workflows/build.yml to what you consider apropiate for release.

**Comment by jannahastings** [comment]
That's awesome, thank you! I would be glad to merge this into the main repo, could you create a PR?

**Comment by areleu** [comment]
closed by #4
