### ISSUE TITLE
Disjointness axioms are not parsed properly

### ISSUE THREAD

**Issue by MGlauer** [jannahastings/py-horned-owl#8]
I tried to load a number of [disjointness axioms](https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi-disjoints.owl) using py-horned-owl, but the resulting disjointness axioms do not contain the target class:

```
>>> onto_dis = pyhornedowl.open_ontology("chebi-disjoints.owl")
>>> onto_dis.get_axioms_for_iri("http://purl.obolibrary.org/obo/CHEBI_15356")
['AxiomKind::DisjointClasses']
```

what I would expect is something like

`['AxiomKind::DisjointClasses', 'http://purl.obolibrary.org/obo/CHEBI_23509']`

**Comment by cmungall** [comment]
I'm not able to replicate using 0.2.1

```python
>>> onto_dis = pyhornedowl.open_ontology("chebi-disjoints.owl")
>>> onto_dis.get_axioms_for_iri("http://purl.obolibrary.org/obo/CHEBI_15356")
[['AxiomKind::DisjointClasses', 'http://purl.obolibrary.org/obo/CHEBI_15356', 'http://purl.obolibrary.org/obo/CHEBI_23509']]
```

**Comment by jannahastings** [comment]
@MGlauer , were the disjointness axioms in a separate file? Horned-OWL doesn't yet load axioms from OWL imports automatically, so you have to use `robot merge` first. This is high on the list for developments in the future.

**Comment by b-gehrke** [comment]
Horned-OWL does support imports now and with the current version of py-horned-owl I cannot reproduce the original bug.
